### PR TITLE
add guides/tutorials section

### PR DESCRIPTION
**Pull request by aviramha**
I thought it'd be nice to have a collection of third party guides/tutorials!

### CODE REVIEW

**Review by clux — APPROVED** [review]
Great idea, thank you!

**Comment by clux** [comment]
Article is great as well! Not that many up-to-date resources like this out there so it's nice to see.

BTW; is returning an `APIResource` on an http route something you need to integrate with api discovery? We could probably add a `Resource` to -> `APIResource` converter helper in `kube-core`.

**Comment by DmitryDodzin** [comment]
Yes as far as I see Kubernetes requires `APIService`s to return `APIResourceList` on https route witch in turn is a `group_version` and a array of `APIResource`s. The group version will determine what api routes the `APIService` will receive, and the `APIResource` is a way to add resources. 

A `Resource` to -> `APIResource` all the required field ones like `name`, `kind` and `namespaced` can be copied over from `Resource` 👍 the rest are optional so can be added relatively simply afterwards by the user.

**Comment by DmitryDodzin** [comment]
Since were on this topic I do have one more inconvenience, If creating CustomResource with derive macro I can't use `k8s_openapi::List` in my routes and `ObjectList<T>` doesn't quite serialize to full api object with `apiVersion` & `kind` fields. 
To work around this in our operator we created `RestfulList<T>` that behaves similarly to `k8s_openapi::List<T>` when serializing but with `kube::Resource` instead of `ListableResource` (though had to limit the trait to `Resource<DynamicType = ()>`)

Could this be a bit of a misuse for derive macro? I was thinking maybe there is a place for `kube::APIResource` macro that works just like CustomResource macro but also can help with lists and also create all the customizations needed for the `Resource` to -> `APIResource` creation
```rust
#[derive(ApiResource, Clone, Debug, Deserialize, Serialize, JsonSchema)]
#[kube(
    group = "clux.dev",
    version = "v1",
    kind = "Foo",
    namespaced,
    list_kind = "FooList",
    verbs = "list,get"
)]
struct FooSpec {
    info: String,
}
```

**Comment by clux** [comment]
Hey @DmitryDodzin , I have created an issue for the first case, that should be easily solvable on our side.

For the `List` part, we can possibly do that as well - our `ObjectList` is pretty dumb, and was basically only designed to cater for deserialization + easy iteration - so we could probably extend it. Are you able to open an issue on kube direct for this? It would be useful to see the source for what you are doing with `RestfulList<T>` as i couldn't find it within farm-operator or the org.

Is `k8s_openapi::List` required for you as an interface for extension apiservices?

**Pull request merged**
